{{- if and (not .Values.existingSecret) (or .Values.secrets .Values.aws.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "am-bot.fullname" . }}-secrets
  labels:
    {{- include "am-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if and .Values.aws.enabled (not .Values.aws.existingSecret) }}
  {{- range $key, $value := .Values.aws.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
